mindmap
  root((Inscrit))
    
    Dire 
      Dire["Je veux m'assurer que mes informations sont correctement enregistrées."]
      Dire["Je souhaite que le test soit clair et adapté à mon niveau."]
      Dire["Je veux connaître mes résultats rapidement après l'évaluation."]

    Fait
      Fait["Remplit un formulaire d'inscription en ligne."]
      Fait["Participe à un test d'évaluation initiale."]
      Fait["Consulte les résultats "]

    Besoin
      Besoin["Un formulaire simple et intuitif pour s'inscrire."]
      Besoin["Un test d'évaluation adapté aux compétences initiales."]
      Besoin["Un accès rapide et clair aux résultats et recommandations."]
