@startuml
left to right direction

actor "Responsable de formation" as Admin
actor "Apprenant" as Apprenant

rectangle "Gestion des Inscriptions et Tests" {
  usecase "Remplir un formulaire d'inscription" as UC1
  usecase "Passer le test d'évaluation" as UC2
  usecase "Accès aux statistiques" as UC3
  usecase "Gérer les questions" as UC4

}

Admin -- UC3 
Admin -- UC4 
Apprenant -- UC1
Apprenant -- UC2 

@enduml
