
classDiagram
    direction LR
    
    class Inscrit {
        +int id
        +string nom
        +string prenom
        +string email
        +string tel
        +string niveau_scolaire
        +Date date_naiss
        +string adresse  
    }

    class Inscription {
        +int id
        +Date date
        +int test_id
        +int Inscrit_id
        +float score
    }
        class Test {
        +int id
        +string nom
        +Date date_debut
        +Date date_fin
        
    }
 
    class Question {
        +int id
        +string question_text
        +int test_id
    }

    class Option {
        +int id
        +string text
        +boolean is_correct
        +int question_id
    }

 
    Inscrit "1" --> "1" Inscription 
    Inscription "*" <-- "1" Test 
    Test "1" --> "*" Question
    Question "1" --> "*" Option
