classDiagram
direction LR
    class Inscrit {
        +int idInscrit
        +String nom
        +String prenom
        +String email
        +String motDePasse
        +String specialisation
        +string tel
        +string niveau_scolaire
        +date date_naiss
        +string adresse
    }

    class Test {
        +int idTest
        +Date datePassation
        +int duree
        +int resultat
    }
  
    class Question {
        +int idQuestion
        +String enonce
    }
    class Option {
        +int idOption
        +String texteOption
        +bool estCorrecte
    }

  

    Inscrit "1" --> "1" Test 
    Test "*" --> "*" Question
    Question "1" --> "*" Option     
  
